apiVersion: crd.withlazers.dev/v1
kind: SecretTemplate
metadata:
  annotations:
  name: my-account-credentials
  namespace: default
spec:
  annotations:
    dev.withlazers.operator.secret-sync-operator/namespace: "mccs-*"
    dev.withlazers.operator.secret-sync-operator/enabled: "true"
  data:
    key:
      plain: my-service
    password:
      generate:
        digits: true
        length: 64
        letters: true
        lowercase: false
        must_custom_alphabet: false
        must_digits: false
        must_letters: false
        must_lowercase: false
        must_symbols: false
        must_uppercase: false
        symbols: false
        uppercase: false
