apiVersion: crd.withlazers.dev/v1
kind: SecretTemplate
metadata:
  name: my-account-credentials
  namespace: default
spec:
  annotation:
    target-namespaces: mccs-*
  data:
    key:
      plain: my-service
    password:
      generate:
        letters: true
        digits: true
        length: 64
