name: Check
on:
  push:
    branches:
      - 'main'

jobs:
  check:
    runs-on: 'ubuntu-20.04'
    strategy:
      matrix:
        operator:
        - secret-sync-operator
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2

    - name: Check if there are changes to ${{ matrix.operator }}
      id: repo_changed
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        set +e
        if [ "GITHUB_REF" = 'refs/heads/main' ]; then
          if git diff --name-only HEAD^ HEAD | grep -q "^${{ matrix.operator }}"; then
            echo "::set-output name=changed::1"
          else
            echo "::set-output name=changed::0"
          fi
        else
          echo "::set-output name=changed::1"
        fi

    # Cargo Checks
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: check
        args: >
          --manifest-path ${{ matrix.operator }}/Cargo.toml
          --verbose
