name: demo
on:
  push:
    branches:
      - 'main'

jobs:
  docker_push:
    runs-on: 'ubuntu-20.04'
    strategy:
      matrix:
        operator:
        - secret-sync-operator
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: ubuntu-20

    - name: Check if there are changes to ${{ matrix.operator }}
      id: repo_changed
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        set +e
        if [ "GITHUB_REF" = 'refs/heads/main' ]; then
          if git diff --name-only HEAD^ HEAD | grep -q "^${{ matrix.operator }}"; then
            echo "::set-output name=changed::1"
          else
            echo "::set-output name=changed::0"
          fi
        else
          echo "::set-output name=changed::1"
        fi

    # Cargo Checks
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: check
        args: >
          --manifest-path ${{ matrix.operator }}/Cargo.toml
          --verbose

    # Docker
    - name: Docker meta
      if: ${{ steps.repo_changed.outputs.changed == '1' }}
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          withlazers/${{ matrix.operator }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Login to DockerHub
      if: ${{ steps.repo_changed.outputs.changed == '1' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      if: ${{ steps.repo_changed.outputs.changed == '1' }}
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: ./${{ matrix.operator }}
