name: release
on:
  push:
    tags:
      - '*-v[0-9]*.[0-9]*.[0-9]*'
jobs:
  release:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Get Short Ref
      id: gitref
      run: echo "::set-output name=result::$(git rev-parse --short HEAD)"

    - name: Extract Operator from Tag
      id: op_name
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\/(.*)-v([0-9]*.[0-9]*.[0-9]*)/, '\1');

    - name: Extract Version from Tag
      id: op_version
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\/(.*)-v([0-9]*.[0-9]*.[0-9]*)/, '\2');

    - name: Print Informations
      run: |
        echo "Operator Name:    ${{steps.op_name.outputs.result}}"
        echo "Operator Version: ${{steps.op_version.outputs.result}}"
        echo "Git Ref:          ${{steps.gitref.outputs.result}}"

    - name: Check If Versions Match
      run: |
        cd "${{steps.op_name.outputs.result}}"
        test "$(cargo pkgid | cut -d'#' -f 2)" = "${{steps.op_version.outputs.result}}"

    # Docker
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          withlazers/${{ steps.op_verion.outputs.result }}
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          sha-${{steps.gitref.outputs.result}}
          ${{steps.op_version.outputs.result}}
        labels: ${{ steps.meta.outputs.labels }}
        context: ./${{ steps.op_verion.outputs.result }}

    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v') && success
      with:
        files: |
          target/x86_64-unknown-linux-musl/release/tpl

